import { Button, Paper, Select, Stack, Text, TextInput, Textarea, Title } from "@mantine/core";
import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import { getContacts } from "../../services/contactService";
import { getEmailTemplates, type EmailTemplate } from "../../services/emailTemplateService";
import { sendEmail } from "../../services/emailSendService";
export default function ComposeEmail() {
  const [contacts, setContacts] = useState<{ value: string; label: string }[]>([]); const [templates, setTemplates] = useState<EmailTemplate[]>([]); const [contactId, setContactId] = useState<string | null>(null); const [templateId, setTemplateId] = useState<string | null>(null); const [subject, setSubject] = useState(""); const [body, setBody] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { void Promise.all([getContacts(), getEmailTemplates()]).then(([contactData, templateData]) => { setContacts(contactData.map((contact) => ({ value: contact.id, label: `${contact.first_name} ${contact.last_name ?? ""} — ${contact.companies?.name ?? "Company"} (${contact.email})` }))); setTemplates(templateData); }).catch(() => toast.error("Email contacts or templates could not be loaded.")); }, []);
  function chooseTemplate(id: string | null) { setTemplateId(id); const template = templates.find((item) => item.id === id); if (template) { setSubject(template.subject); setBody(template.body); } }
  async function send() { if (!contactId || !subject.trim() || !body.trim()) { toast.error("Choose a contact and complete the email."); return; } if (!window.confirm("Send this email now?")) return; setSaving(true); try { await sendEmail(contactId, templateId, subject, body); toast.success("Email sent and activity recorded."); setContactId(null); setTemplateId(null); setSubject(""); setBody(""); } catch (error) { toast.error(error instanceof Error ? error.message : "Email could not be sent."); } finally { setSaving(false); } }
  return <Paper maw={820} withBorder p="md"><Stack><div><Title order={1}>Compose Email</Title><Text c="dimmed">Send from the connected CACO mailbox. A record is automatically added to the company activity history.</Text></div><Select label="Contact" data={contacts} value={contactId} onChange={(value) => setContactId(typeof value === "string" ? value : null)} searchable required /><Select label="Start from a template (optional)" data={templates.map((template) => ({ value: template.id, label: template.name }))} value={templateId} onChange={chooseTemplate} clearable /><TextInput label="Subject" value={subject} onChange={(event) => setSubject(event.currentTarget.value)} required /><Textarea label="Message" minRows={12} value={body} onChange={(event) => setBody(event.currentTarget.value)} required /><Button onClick={() => void send()} loading={saving}>Send email</Button></Stack></Paper>;
}
