import { Button, Group, Paper, Stack, Switch, Table, Text, TextInput, Textarea, Title } from "@mantine/core";
import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import { useAuth } from "../../contexts/AuthContext";
import { getEmailTemplates, saveEmailTemplate, setEmailTemplateActive, type EmailTemplate } from "../../services/emailTemplateService";
const blank = { name: "", subject: "", body: "" };
export default function EmailTemplates() {
  const { profile } = useAuth(); const isAdmin = profile?.role === "admin"; const [templates, setTemplates] = useState<EmailTemplate[]>([]); const [form, setForm] = useState(blank); const [editingId, setEditingId] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  async function load() { try { setTemplates(await getEmailTemplates()); } catch { toast.error("Email templates could not be loaded."); } }
  useEffect(() => { void load(); }, []); function update(field: keyof typeof form, value: string) { setForm((current) => ({ ...current, [field]: value })); }
  async function save() { if (!form.name.trim() || !form.subject.trim() || !form.body.trim()) { toast.error("Name, subject and message are required."); return; } setSaving(true); try { await saveEmailTemplate(form, editingId ?? undefined); setForm(blank); setEditingId(null); await load(); toast.success("Template saved."); } catch { toast.error("Template could not be saved."); } finally { setSaving(false); } }
  async function toggle(template: EmailTemplate) { try { await setEmailTemplateActive(template.id, !template.is_active); await load(); } catch { toast.error("Template status could not be updated."); } }
  return <Stack gap="md"><div><Title order={1}>Email Templates</Title><Text c="dimmed">Shared marketing messages for introductions, catalogues and product information.</Text></div>{isAdmin && <Paper withBorder p="md"><Stack><TextInput label="Template name" value={form.name} onChange={(event) => update("name", event.currentTarget.value)} /><TextInput label="Email subject" value={form.subject} onChange={(event) => update("subject", event.currentTarget.value)} /><Textarea label="Message" minRows={8} value={form.body} onChange={(event) => update("body", event.currentTarget.value)} /><Group justify="flex-end">{editingId && <Button variant="default" onClick={() => { setEditingId(null); setForm(blank); }}>Cancel</Button>}<Button onClick={() => void save()} loading={saving}>{editingId ? "Save changes" : "Add template"}</Button></Group></Stack></Paper>}<Paper withBorder p="md"><Table striped><Table.Thead><Table.Tr><Table.Th>Name</Table.Th><Table.Th>Subject</Table.Th>{isAdmin && <Table.Th>Status</Table.Th>}{isAdmin && <Table.Th>Action</Table.Th>}</Table.Tr></Table.Thead><Table.Tbody>{templates.map((template) => <Table.Tr key={template.id}><Table.Td>{template.name}</Table.Td><Table.Td>{template.subject}</Table.Td>{isAdmin && <Table.Td><Switch checked={template.is_active} onChange={() => void toggle(template)} label={template.is_active ? "Active" : "Hidden"} /></Table.Td>}{isAdmin && <Table.Td><Button size="xs" variant="default" onClick={() => { setEditingId(template.id); setForm({ name: template.name, subject: template.subject, body: template.body }); }}>Edit</Button></Table.Td>}</Table.Tr>)}{templates.length === 0 && <Table.Tr><Table.Td colSpan={isAdmin ? 4 : 2}>No email templates available.</Table.Td></Table.Tr>}</Table.Tbody></Table></Paper></Stack>;
}
