import { Button, Group, Paper, Select, Stack, Table, Text, TextInput, Title } from "@mantine/core";
import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import { getCompanies } from "../../services/companyService";
import { getInvitations, inviteUser, type Invitation } from "../../services/invitationService";

export default function Invitations() {
  const [email, setEmail] = useState(""); const [companyId, setCompanyId] = useState<string | null>(null); const [role, setRole] = useState<"admin" | "member">("member"); const [companies, setCompanies] = useState<{ value: string; label: string }[]>([]); const [invitations, setInvitations] = useState<Invitation[]>([]); const [saving, setSaving] = useState(false);
  async function load() { try { const [companyData, invitationData] = await Promise.all([getCompanies(), getInvitations()]); setCompanies(companyData.map((company) => ({ value: company.id, label: company.name }))); setInvitations(invitationData); } catch { toast.error("Invitations could not be loaded."); } }
  useEffect(() => { void load(); }, []);
  async function send() { if (!email.trim() || !companyId) { toast.error("Email and company are required."); return; } setSaving(true); try { await inviteUser(email, companyId, role); setEmail(""); setCompanyId(null); setRole("member"); await load(); toast.success("Invitation email sent."); } catch (error) { toast.error(error instanceof Error ? error.message : "Invitation could not be sent."); } finally { setSaving(false); } }
  return <Stack gap="md"><div><Title order={1}>Invite User</Title><Text c="dimmed">Invite-only access: Admin assigns the company and role before the recipient creates their password.</Text></div><Paper withBorder p="md"><Stack><TextInput label="Email address" type="email" required value={email} onChange={(event) => setEmail(event.currentTarget.value)} /><Select label="Company" data={companies} value={companyId} onChange={(value) => setCompanyId(typeof value === "string" ? value : null)} required searchable /><Select label="Role" data={[{ value: "member", label: "Member" }, { value: "admin", label: "Admin" }]} value={role} onChange={(value) => setRole((value as "admin" | "member") || "member")} /><Group justify="flex-end"><Button onClick={() => void send()} loading={saving}>Send invitation</Button></Group></Stack></Paper><Paper withBorder p="md"><Title order={3}>Invitation history</Title><Table mt="md" striped><Table.Thead><Table.Tr><Table.Th>Email</Table.Th><Table.Th>Company</Table.Th><Table.Th>Role</Table.Th><Table.Th>Status</Table.Th><Table.Th>Sent</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{invitations.map((invitation) => <Table.Tr key={invitation.id}><Table.Td>{invitation.email}</Table.Td><Table.Td>{invitation.companies?.name ?? "—"}</Table.Td><Table.Td>{invitation.role}</Table.Td><Table.Td>{invitation.status}</Table.Td><Table.Td>{new Date(invitation.created_at).toLocaleString()}</Table.Td></Table.Tr>)}{invitations.length === 0 && <Table.Tr><Table.Td colSpan={5}>No invitations sent yet.</Table.Td></Table.Tr>}</Table.Tbody></Table></Paper></Stack>;
}
